# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.5
      
    - name: Install dependencies
      run: npm install
    
    - name: Build
      run: npm run build
    
    - name: Zip Release
      if: github.event == 'release'
      uses: TheDoctor0/zip-release@0.4.2
      with:
          path: build/trains
          filename: trains.zip
    
    - name: Upload artifact and release
      if: github.event == 'release'
      uses: nanoufo/action-upload-artifacts-and-release-assets@main
      with:
        path: trains.zip
        upload-release-files: true
        release-upload-url: ${{ github.event.release.upload_url }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
