# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.20.3
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.5
      with:
        node-version: '17.6.0'
        cache: 'pnpm'
      
    - name: Install dependencies
      run: pnpm install

    - name: Run build
      run: pnpm run build

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Datapack
        path: build/trains/
 
